#! /bin/sh

# run the xrandr command if an external monitor is connected to the
# laptop.  This must be executed before the polybar command, so that
# polybar can set the two separate bars properly.
my_laptop_external_monitor=$(xrandr --query | grep 'DP-1')
if [[ $my_laptop_external_monitor = *connected* ]]; then
	xrandr --output eDP-1 --mode 1920x1080 --output DP-1 --primary --mode 3440x1440 --right-of eDP-1
fi

$XDG_CONFIG_HOME/polybar/launch.sh

pgrep -x sxhkd > /dev/null || sxhkd &

# load Xresources
xrdb -merge $HOME/.Xresources

if [[ $my_laptop_external_monitor = *connected* ]]; then
	bspc monitor DP-1 -d 1 2 3
	bspc monitor eDP-1 -d 4 5 6
else
	bspc monitor eDP-1 -d 1 2 3
fi

bspc config border_width         3
bspc config window_gap           5

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config focus_follows_pointer true
bspc config pointer_follows_monitor true

bspc config focused_border_color \#466349
bspc config normal_border_color \#303030

# bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a google_chrome_stable flags=locked
# bspc rule -a mplayer2 state=floating
# bspc rule -a Kupfer.py focus=on
# bspc rule -a Screenkey manage=off
