#!/bin/bash

env_file="${HOME}/.config/bspwm/automatic_tabbed_window_name"

bspc subscribe node_add | while read -r line; do
    # Use the environment variable, with a default fallback in case it's not set
    tabbed_class_name=$(cat "$env_file")
    echo "the current tabbed_class_name is $tabbed_class_name"

    new_window_id=$(echo $line | awk '{print $5}')
    echo "new window id $new_window_id"
    new_window_name=$(xprop -id $new_window_id WM_CLASS | awk '{print $4}' | tr -d \")
    echo "new window name $new_window_name"

    if [ "$new_window_name" = "matplotlib" ]; then
        echo "FOUND"
        # Check if there is a tabbed instance open
        tab_window_id=$(xdotool search --classname "^$tabbed_class_name")
        if [ -z "$tab_window_id" ]; then
            # Open the tabbed window
            echo "no existing $tabbed_class_name, opening new $tabbed_class_name"
            tabbed -n $tabbed_class_name&
            sleep 0.1
            tab_window_id=$(xdotool search --classname "^$tabbed_class_name")
            echo "tab_window_id $tab_window_id"
        else
            echo "tabbed windows exist"
        fi
        xdotool windowreparent $new_window_id $tab_window_id
    fi
done
