#!/bin/sh

# bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a google_chrome_stable flags=locked
bspc rule -a zoom state=floating
bspc rule -a Peek state=floating
bspc rule -a windows_rules state=floating
bspc rule -a xprop state=floating
bspc rule -a timeular desktop=6
# bspc rule -a matplotlib desktop=3
# bspc rule -a mplayer2 state=floating
# bspc rule -a Kupfer.py focus=on
# bspc rule -a Screenkey manage=off
